# Bienvenue {.unnumbered}

Ceci est le site de la 2e édition de **« R pour la science des données »**.
Ce livre vous apprendra à faire de la science des données avec R : vous apprendrez à importer vos données dans R, à leur donner la structure la plus utile, à les transformer et à les visualiser.

Dans ce livre, vous trouverez un ensemble de compétences pour la science de données.
Tout comme un chimiste apprend à nettoyer des tubes à essai et à équiper un laboratoire, vous apprendrez à nettoyer des données et à construire des graphiques --- et bien d'autres choses encore.
Ce sont les compétences qui rendent la science de données possible, et vous trouverez ici les meilleures pratiques pour réaliser chacune d'entre elles avec R.
Vous apprendrez à utiliser la grammaire des graphiques, la programmation lettrée et la recherche reproductible pour gagner du temps.
Vous apprendrez aussi à gérer vos ressources cognitives pour faciliter les découvertes lorsque vous manipulez, visualisez et explorez des données.

Ce site est et restera toujours gratuit, sous licence [CC BY-NC-ND 3.0](https://creativecommons.org/licenses/by-nc-nd/3.0/us/).
Si vous souhaitez une copie physique du livre, vous pouvez la commander sur [Amazon](https://www.amazon.com/dp/1492097403?&tag=hadlwick-20).
Si vous appréciez lire ce livre gratuitement et souhaitez contribuer en retour, faites un don à [Kākāpō Recovery](https://www.doc.govt.nz/kakapo-donate) : le [kākāpō](https://www.youtube.com/watch?v=9T1vfsHYiKY) (qui figure sur la couverture de R4DS) est un perroquet en danger critique d'extinction, endémique de la Nouvelle-Zélande ; il n'en reste que 236.

Si vous parlez une autre langue, les traductions librement disponibles de la 1ère édition pourraient vous intéresser :

-   [Espagnol](http://es.r4ds.hadley.nz)
-   [Italien](https://it.r4ds.hadley.nz)
-   [Turc](https://tr.r4ds.hadley.nz)
-   [Portugais](https://pt.r4ds.hadley.nz)

ainsi que celles de la 2ème édition

-   [Espagnol](https://davidrsch.github.io/r4ds-es/)
-   [Vietnamien](https://vn.r4ds.hadley.nz/)

Vous trouverez des propositions de réponses aux exercices du livre sur <https://mine-cetinkaya-rundel.github.io/r4ds-solutions>.

Veuillez noter que R4DS suit un [Code de conduite des contributeurs](https://contributor-covenant.org/version/2/0/CODE_OF_CONDUCT.html).
En contribuant à ce livre, vous acceptez d'en respecter les termes.

# À propos de la traduction {.unnumbered}

Cette traduction en français du livre "R pour la Science de Données (2e)" est un projet personnel de [Diane Thierry](https://www.linkedin.com/in/diane-thierry-b22099193/), visant à faciliter l'étude et l'appropriation de son contenu par la communauté R francophone. 

La traduction a été réalisée à l'aide de l'IA générative Claude et reprise pour garantir une bonne cohérence d'ensemble. Si vous détectez des erreurs de traduction, merci d'ouvrir une *issue* ou une *pull request* sur [le repo dédié](https://github.com/DianeThy/r4ds-fr). 

